FROM ubuntu:latest

RUN mkdir /stuff
WORKDIR /stuff

RUN apt-get update && \
    apt-get install python3.7 python3-pip -y && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2

RUN pip3 install python-twitter

COPY app.py /stuff/

CMD python3 /stuff/app.py